# Generated by Django 5.1.7 on 2025-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IrisPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sepal_length", models.FloatField()),
                ("sepal_width", models.FloatField()),
                ("petal_length", models.FloatField()),
                ("petal_width", models.FloatField()),
                ("prediction", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
